name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Generate temporary keystore
      run: keytool -genkey -v -storetype pkcs12 -keystore store.p12 -storepass android -alias android -keyalg RSA -keysize 2048 -validity 10000 -dname CN=CI
    - name: Write retro.properties
      run: |
        cat >retro.properties <<EOF
        storeFile=$PWD/store.p12
        keyAlias=android
        storePassword=android
        keyPassword=android
        EOF
    - name: Build with Gradle
      run: ./gradlew build
  release:
    name: Release APK
    needs: apk
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} 
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-debug.apk
          asset_name: MensaApp.apk
          asset_content_type: application/zip
name: Minimal Android CI Workflow

on:

  workflow_dispatch

  push:

    branches:

      - master

    tags:

      - 'v*'

jobs:

   

  apk:

    name: Generate APK

    needs: test

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: set up JDK 11

        uses: actions/setup-java@v2

        with:

          java-version: '11'

          distribution: 'temurin'

          cache: gradle

      - name: Generate temporary keystore

        run: keytool -genkey -v -storetype pkcs12 -keystore store.p12 -storepass android -alias android -keyalg RSA -keysize 2048 -validity 10000 -dname CN=CI

      - name: Write retro.properties

        run: |

        cat >retro.properties <<EOF

        storeFile=$PWD/store.p12

        keyAlias=android

        storePassword=android

        keyPassword=android

        EOF

      - name: Build with Gradle

        run: ./gradlew build

  release:

    name: Release APK

    needs: apk

    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:

      - name: Download APK from build

        uses: actions/download-artifact@v1

        with:

          name: apk  

      - name: Create Release

        id: create_release

        uses: actions/create-release@v1

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

        with:

          tag_name: ${{ github.ref }}

          release_name: Release ${{ github.ref }} 

      - name: Upload Release APK

        id: upload_release_asset

        uses: actions/upload-release-asset@v1.0.1

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:

          upload_url: ${{ steps.create_release.outputs.upload_url }}

          asset_path: apk/app-debug.apk

          asset_name: MensaApp.apk

          asset_content_type: application/zip ki
